### ISSUE TITLE
Theo's Bot issues for TAFI

### ISSUE THREAD

**Issue by TheOriginalSoni** [theopolisme/theobot#11]
These are the issues/feature requests that I have, which are yet not resolved. (I may be repeating what I said in other places, so my apologies for the redundancy)

1) A way to notify all wikiprojects that the article is being selected as TAFI, maybe.
2) A list of plain links for the entire schedule
3) Update the schedule archive at https://en.wikipedia.org/wiki/Wikipedia:Today%27s_articles_for_improvement/Archives/2013_schedule whenever the current week is removed
4) Optimise and find a way to add a new month at the listings at https://en.wikipedia.org/wiki/Wikipedia:Today%27s_articles_for_improvement/Archives/Unsuccessful_Nominations, https://en.wikipedia.org/wiki/Wikipedia:Today%27s_articles_for_improvement/Archives and https://en.wikipedia.org/wiki/Wikipedia:Today%27s_articles_for_improvement/Archives/Successful_Nominations every month so these pages do not stay outdated.
5) Spelling of archived in https://en.wikipedia.org/wiki/Wikipedia:Today%27s_articles_for_improvement/Archives/Unsuccessful_Nominations/May_2013
6) Update the https://en.wikipedia.org/wiki/Wikipedia:Today%27s_articles_for_improvement/Archives/Successful_Nominations page whenever the schedule for a week is prepared (Note - Don't do the archiving while moving to HA, as discussions continue there, and future plans are for To-Do lists).
7) A possible option to maybe automate the picture box updation?

**Comment by theopolisme** [comment]
I've split this apart into separate issues, which can be viewed at [https://github.com/theopolisme/theobot/issues?page=1&state=open]
