### ISSUE TITLE
TAFI - Notify wikiprojects

### ISSUE THREAD

**Issue by theopolisme** [theopolisme/theobot#12]
A way to notify all wikiprojects that the article is being selected as TAFI, maybe.

**Comment by theopolisme** [comment]
More complicated than it seems. Requires parsing of the talk page and transcluded template to generate names of relevant WikiProjects--once we have the names, though, posting a message is easy.

@TheOriginalSoni: is there a template you're using to notify folks?

**Comment by TheOriginalSoni** [comment]
{{TAFI project notice|Article=Article|Sign=~~~~}}

**Comment by theopolisme** [comment]
BRFA open -- [task 17](https://en.wikipedia.org/wiki/Wikipedia:Bots/Requests_for_approval/Theo%27s_Little_Bot_17)

**Comment by TheOriginalSoni** [comment]
Note- TAFI are no longer on the main page, pending a consensus to put it back

**Comment by theopolisme** [comment]
@TheOriginalSoni: What does this mean for the bot? Which tasks (specifically) need to be disabled?

**Comment by TheOriginalSoni** [comment]
I thought you would understand noting where I'd posted this. Specifically, the line stating the main page will be definitely removed. The notification in their entirety might be also removed for now if required

**Comment by theopolisme** [comment]
No, I understand that--I meant, does the task that adds {{TAFI}} need to be disabled as well?

**Comment by TheOriginalSoni** [comment]
I am not sure. I doubt it, but it's prudent to ping the project and ask.

[Specifically, notifying the project that its being disabled would work better to get the job done, as that would set everyone in motion again on getting the other pending work completed (Getting it on the main page, deciding properly over the tafi template etc)

**Comment by theopolisme** [comment]
Thread opened at https://en.wikipedia.org/wiki/Wikipedia_talk:Today%27s_articles_for_improvement#Disabling_bot

**Comment by theopolisme** [comment]
Task approved.

**Comment by TheOriginalSoni** [comment]
Could we re-start the scheduling and the adding of the {{TAFI}} template on the articles? It appears we still have an active Social Media outreach system for TAFI. Restarting the inactive functions of theobot for TAFI would be very helpful.

(The design is still being worked on as we speak. I'm trying to collaborate with Technical 13 on the same)

**Comment by theopolisme** [comment]
The addition of {{TAFI}} and {{Former TAFI}} has been running for the past few weeks, IIRC...it definitely ran this past Sunday. All other tasks should be running as well.

**Comment by TheOriginalSoni** [comment]
http://en.wikipedia.org/wiki/Wikipedia:Today%27s_articles_for_improvement/Schedule
contains
the previous weeks too. Shouldnt this be having only the current week and
the few weeks after it? (Sorry for the confusion, but that's what made me
think the templating is on hold)

[Same for http://en.wikipedia.org/wiki/Wikipedia:Today%27s_articles_for_improvement/Schedule/static]

**Comment by theopolisme** [comment]
Fixing.

**Comment by theopolisme** [comment]
Should be fixed.
