### ISSUE TITLE
TAFI - picture box

### ISSUE THREAD

**Issue by theopolisme** [theopolisme/theobot#13]
A possible option to maybe automate the picture box updation?

**Comment by theopolisme** [comment]
@TheOriginalSoni: by "automate picture box updation," do you mean _automatically select pictures_? I think that's going too far, personally. The human eye still has its uses ;)

**Comment by TheOriginalSoni** [comment]
No. Currently, the change of picture box is done manually at the given time. We can set it up so it updates with the next week's picture and caption at the week's change.

ie the picture and caption will be chosen by us, but the bot makes sure its updated on time

**Comment by theopolisme** [comment]
Hmm, sure, this can be done. I'll look into it tomorrow afternoon probably.

**Comment by theopolisme** [comment]
@TheOriginalSoni: So, as far as implementing this goes, would it work to have a page, say Wikipedia:Today's articles for improvement/Schedule/pictures, with the following contents:

``` mediawiki
<!----------------ADD PICTURES HERE--------------->
<!-- Copy and paste the following for each week --><noinclude>

{{/week
|year = {{subst:CURRENTYEAR}} <!-- don't edit this line -->
|number = ## <!-- enter the week's number -->
|picture = File:Example.png <!-- do not add the brackets! -->
|caption = Sample caption here <!-- Enter your desirec caption -->
}}

</noinclude><!-- LIST WEEKS BELOW HERE -->
```

The idea would be then that you (or whoever else) would just add pictures to that page using the meta-template, and then the bot would come along and add them to the master picture template when the time came around. Your thoughts?

**Comment by TheOriginalSoni** [comment]
http://cdn.memegenerator.net/instances/400x/38502181.jpg

(Never doubt the insanity of a tired me)

**Comment by theopolisme** [comment]
On hold until TAFI issues sorted out
