### ISSUE TITLE
TAFI - more archiving

### ISSUE THREAD

**Issue by theopolisme** [theopolisme/theobot#18]
Update the https://en.wikipedia.org/wiki/Wikipedia:Today%27s_articles_for_improvement/Archives/Successful_Nominations page whenever the schedule for a week is prepared (Note - Don't do the archiving while moving to HA, as discussions continue there, and future plans are for To-Do lists).

**Comment by theopolisme** [comment]
@TheOriginalSoni: could you clarify what needs to be done here? I have to admit I don't really understand what you're requesting--an example would be great.

**Comment by TheOriginalSoni** [comment]
Currently, we have only the schedule archive which is updated. What should have also been updated is this Successful Nominations archive, which should have been done when the schedule is prepared (ie, when the nominator comments and other votes comments get "destroyed" - We have no way to access them well currently.)

So this archive would contain all the updated successful nominations along with the comments.

**Comment by theopolisme** [comment]
On hold until TAFI issues sorted out
