### ISSUE TITLE
Bot-generated whining

### ISSUE THREAD

**Issue by John-Nagle** [theopolisme/theobot#2]
Re: Your bot is complaining that:
    File:German-sdkfz7.jpg
    File:Israelprojectlogo.jpg
    File:Stopbadwareyellowalert.png
    File:Pontiac1961.jpg
    File:Buick1961.jpg
    File:Woodruff1.png

"are missing a description and/or other details on their image description pages."
If you wish to add a description to those images, you are free to do so. However, I have no obligation to do so.

**Comment by theopolisme** [comment]
You can stop the bot from notifying you by adding the following to the top of your talk page:
`{{bots|deny=Theo's Little Bot}}`
