### ISSUE TITLE
Bot acting weirdly at static links?

### ISSUE THREAD

**Issue by TheOriginalSoni** [theopolisme/theobot#24]
It appears that the bot is acting weirdly at Static. See https://en.wikipedia.org/w/index.php?title=Wikipedia:Today%27s_articles_for_improvement/Schedule/static&diff=next&oldid=559141589 and all subsequent edits. Also, the static schedule is now one week behind the actual schedule. Is that supposed to happen?

**Comment by theopolisme** [comment]
Hmm...I've killed the task temporarily. Looking into now.
