### ISSUE TITLE
Sledgehammer - Want to disable just task 2 notifications I found unhelpful.

### ISSUE THREAD

**Issue by elvey** [theopolisme/theobot#30]
The bot left a task 2 notification on my talk page.
How do I disable just this task?

 {{bots|deny=Theo's Little Bot}} is worrisomely broad.

**Comment by theopolisme** [comment]
I [wrote the documentation](http://en.wikipedia.org/w/index.php?title=User%3ATheo%27s_Little_Bot%2Fopt-out&diff=559659574&oldid=550291865) for this a while ago, but for some reason never implemented it in the source code. I'll get on this in a few hours.

**Comment by theopolisme** [comment]
Instructions can be found [here](http://en.wikipedia.org/wiki/User:Theo%27s_Little_Bot/opt-out).
