### ISSUE TITLE
Scheduling problems at Holding Area... Again

### ISSUE THREAD

**Issue by TheOriginalSoni** [theopolisme/theobot#31]
See http://en.wikipedia.org/w/index.php?title=Wikipedia%3AToday%27s_articles_for_improvement%2FHolding_area&diff=564291708&oldid=563303825 and the previous botched up schedulings at the HA.

**Comment by theopolisme** [comment]
Looking into.

**Comment by theopolisme** [comment]
Looks like it's been messed up for quite a while.

I think this shows the general inactivity surrounding TAFI, first of all. But regardless I will look into a fix.

**Comment by TheOriginalSoni** [comment]
I agree on the inactivity front... The most important hurdle still remains the design of a suitable main page section, which I'm currently trying to work on with Technical13

**Comment by theopolisme** [comment]
Looks like the root of all evil was

```
zodiac article are quite bad. But as [[Maria von Trapp|Maria]] once said "[[ Do-Re-Mi|let's start at the very beginning. 
It's a very good place to start]]". FYI, the Aries article on the constellation is an FA, and the next signs - Taurus,
Gemini & Cancer - all have woeful articles, and get 3300, 4150, and 1600 daily hits respectively. Cmon guys,
we can do better. :D--[[User:Coin945|Coin945]] ([[User talk:Coin945|talk]]) 16:10, 28 April 2013 (UTC)
```

As you can see, it didn't use the {{TAFI nom}} template, which basically messed up everything else. So, seems to be more of a user error than a script error. :/

**Comment by TheOriginalSoni** [comment]
Ugh. So I hope its fixed now?

**Comment by theopolisme** [comment]
Yep, I've tidied the page.

Not many new nominations coming in, though... you're going to stop having a balanced set of articles pretty soon, fwiw.
