### ISSUE TITLE
Should follow user talk page redirects when leaving a message

### ISSUE THREAD

**Issue by Amalthea** [theopolisme/theobot#34]
When leaving a talk page message like {{Add-desc-I}} the bot should follow a user talk page redirect if it finds one.

Example for an edit where it didn't: https://en.wikipedia.org/w/index.php?title=User_talk:Tibetan_Prayer&diff=prev&oldid=568374361

The MediaWiki edit API offers a parameter to resolve redirects automatically that you should be able to use.

**Comment by theopolisme** [comment]
Fixed.

Looking at it now, I should probably just rewrite all of that code; it was my second programming project _ever_ and is basically an unreadable mess..._shrug_.
